import { AGENT_GUIDE_PATH, generateGuide } from '../guide/generate';
import { inspectProject } from '../guide/inspect';
import type { ProjectProfile } from '../guide/types';
import { writeGuide } from '../guide/write';
import { loadWorkspaceSemantics } from '../semantics/load';
import { scanWorkspace } from '../scanner/scan';

// ---------------------------------------------------------------------------
// `a2h guide [path]` — inspect -> generate -> write -> print.
//
// The command is deliberately one-way and offline: it reads the workspace's
// shape, writes one file, and prints what it saw. It never starts the viewer,
// never runs `init`, and never touches `AGENTS.md`. The project's own agent
// decides whether to merge anything from the guide into its own rules.
//
// It reports through its exit code the way `validate` does, because a script
// that regenerates a guide needs to know whether the write was refused.
// ---------------------------------------------------------------------------

export interface GuideRunResult {
  /** 0 when the guide was written, 1 when it was refused. */
  exitCode: number;
  /** Workspace-relative path of the guide. */
  path: string;
  profile: ProjectProfile;
}

export function runGuide(rootDir: string, options: { force?: boolean } = {}): GuideRunResult {
  const scan = scanWorkspace({ rootDir });
  const loaded = loadWorkspaceSemantics(rootDir, scan);
  const profile = inspectProject(scan, loaded);
  const result = writeGuide(rootDir, generateGuide(profile), { force: options.force });

  console.log('');
  console.log('A2H guide');
  console.log('');

  if (!result.written) {
    if (result.code === 'exists') {
      console.log(`  ${AGENT_GUIDE_PATH} already exists and does not appear to be generated by A2H.`);
      console.log('  Use --force to replace it.');
    } else {
      console.log(`  Could not write ${AGENT_GUIDE_PATH}`);
      console.log(`  ${result.reason ?? 'the write was refused'}`);
    }
    console.log('');
    return { exitCode: 1, path: result.path, profile };
  }

  console.log(`  Wrote ${AGENT_GUIDE_PATH}`);
  console.log('');
  console.log('  Detected:');
  for (const line of detectedLines(profile)) console.log(`    ${line}`);
  console.log('');
  console.log("  Add or merge this guidance into your project's AGENTS.md");
  console.log('  if you want coding agents to follow it persistently.');
  console.log('');

  return { exitCode: 0, path: result.path, profile };
}

/**
 * What to show the human as "detected".
 *
 * These come from the profile rather than from a per-repository branch, so a
 * workspace that changes shape changes its own summary. Traits first, then
 * languages, then the directory conventions that matched — the same order the
 * guide itself uses.
 */
export function detectedLines(profile: ProjectProfile): string[] {
  const lines: string[] = [];
  if (profile.traits.dataHeavy) lines.push('data-heavy repository');
  if (profile.traits.codeHeavy) lines.push('code-heavy repository');
  if (profile.traits.documentHeavy) lines.push('document-heavy repository');
  lines.push(...profile.dominantLanguages);
  for (const bucket of profile.buckets) lines.push(bucket.label);
  if (profile.hasManifest) lines.push('existing A2H manifest');
  if (profile.hasAgentsMd) lines.push('AGENTS.md');
  if (profile.hasSensitiveFiles) lines.push('sensitive files (never copied into a view)');

  return lines.length ? [...new Set(lines)] : ['nothing distinctive detected'];
}
