import type { ProjectProfile } from './types';

// ---------------------------------------------------------------------------
// Profile -> `.a2h/agent-guide.md`.
//
// Two properties are load-bearing and both are tested:
//
//   * determinism — the output is a pure function of the profile. No clock, no
//     absolute path, no environment, no iteration order. Two runs over an
//     unchanged workspace must be byte-identical, which is what makes the file
//     safe to regenerate in a git repository.
//   * no tree — the guide describes *how* to present work, never *what* the
//     work is. A generated file listing would be stale the moment it is
//     written, and an agent reading it would trust it.
//
// The body is deliberately handwritten prose rather than a model call: it is
// advice about what a human reads well, which does not improve when it is
// neither deterministic nor reviewable.
// ---------------------------------------------------------------------------

/** Stable machine marker. Overwrite policy keys off exactly this string. */
export const AGENT_GUIDE_MARKER = '<!-- Generated by @tinyviber/a2h. Safe to regenerate. -->';

/** Where the guide lives, relative to the workspace root. */
export const AGENT_GUIDE_PATH = '.a2h/agent-guide.md';

export function generateGuide(profile: ProjectProfile): string {
  // Blocks are joined with a blank line rather than concatenated: every section
  // starts at a heading, and a heading that follows a paragraph on the next
  // line is not a heading in Markdown at all — it renders as prose.
  const blocks: string[][] = [
    [`# A2H producer guide for ${profile.name}`, '', AGENT_GUIDE_MARKER],
    purpose(),
    detectedShape(profile),
    presentationStrategy(profile),
    humanFacingViews(),
    existingSetup(profile),
    artifactGuidance(profile),
    producerWorkflow(),
    validation(),
    boundaries(),
  ];

  const body = blocks
    .map((block) => block.join('\n').replace(/\n{3,}/g, '\n\n').trim())
    .join('\n\n');

  return `${body}\n`;
}

function purpose(): string[] {
  return [
    '## Purpose',
    '',
    'A2H is the human-facing layer over an agent workspace. You produce files;',
    'A2H turns the ones that matter into a page a human can open locally to read,',
    'inspect, compare, judge, and act on. This guide is about leaving work behind',
    'in *this* repository in a shape a human can actually review, rather than',
    'leaving a directory listing and hoping.',
    '',
    'It is written by tooling from the observable shape of the repository —',
    'directory names, file types, and the presence of an A2H manifest. It contains',
    'no secrets and no file contents, and it is safe to regenerate: running the',
    'generator again over an unchanged repository produces the identical file.',
    '',
    'It is also **not part of the A2H protocol**. `.a2h/agent-guide.md` is agent',
    'guidance and nothing more: it is not read as semantics, it never takes part in',
    'the field-level merge that decides what an artifact means, and it is never',
    'rendered as workspace content. The protocol input remains',
    '`.a2h/manifest.json`.',
  ];
}

function detectedShape(profile: ProjectProfile): string[] {
  const { traits } = profile;
  const traitNames: string[] = [];
  if (traits.codeHeavy) traitNames.push('code-heavy');
  if (traits.dataHeavy) traitNames.push('data-heavy');
  if (traits.documentHeavy) traitNames.push('document-heavy');
  if (traits.hasGeneratedOutputs) traitNames.push('has generated outputs');
  if (traits.hasTests) traitNames.push('has tests');

  return [
    '## Detected project shape',
    '',
    `- Traits: ${traitNames.length ? traitNames.join(', ') : 'no strong trait — a small or mixed workspace'}.`,
    `- Languages: ${profile.dominantLanguages.length ? profile.dominantLanguages.join(', ') : 'no code files detected'}.`,
    `- Conventions in use: ${
      profile.buckets.length
        ? profile.buckets.map((b) => `${b.label} (${b.matches.join(', ')})`).join('; ')
        : 'no standard directory convention matched'
    }.`,
    `- A2H manifest: ${profile.hasManifest ? '`.a2h/manifest.json` is present' : 'none present — A2H is inferring from conventions'}.`,
    `- \`AGENTS.md\`: ${profile.hasAgentsMd ? 'present at the repository root' : 'not present at the repository root'}.`,
    `- Sensitive files: ${
      profile.hasSensitiveFiles
        ? 'at least one file is classified credential-like, and none of them was read to produce this guide'
        : 'none classified as credential-like'
    }.`,
    '',
    'No file tree appears above, on purpose. Walk the repository when you need',
    'detail; this list is the coarse shape the guide was generated from, which is',
    'the right resolution for deciding how to present work — not what the work is.',
  ];
}

function presentationStrategy(profile: ProjectProfile): string[] {
  const lines: string[] = [
    '## How to present work in this repository',
    '',
    '- Always curate. The human is looking through A2H precisely because the full',
    '  tree is too much; if the honest answer is "all of it", A2H is not the tool.',
    '- Prefer a few artifacts that answer a question over many that describe a',
    '  process. A human reads the shape first and the detail second.',
  ];

  if (profile.traits.codeHeavy) {
    lines.push(
      '',
      '### Presenting code',
      '',
      'Do not present the whole source tree. Someone reviewing a change wants the',
      'change, not the corpus: the spec or ticket, a short summary of what moved,',
      'the few files that actually changed, the tests that demonstrate it, the diff',
      'itself, screenshots where the change is visible, the relevant log lines, and',
      'the decision being asked of them. Show code by exception — the parts a human',
      'must judge — and let the repository hold the rest.',
    );
  }

  if (profile.traits.dataHeavy) {
    lines.push(
      '',
      '### Presenting data',
      '',
      'Treat the corpus as the source of truth, and do not expose the whole of it',
      'through A2H just because it exists. A view over data is a *materialized*',
      'answer to one question, not a window onto the collection:',
      '',
      '    views/<query>/',
      '      overview.md          what was asked, what was run, what the answer is',
      '      selection.jsonl      the bounded selection the answer rests on',
      '      artifacts/           the charts, tables, or excerpts that carry it',
      '      .a2h/manifest.json   what those files mean and the order to read them in',
      '',
      'The overview is the deliverable, the selection is the evidence, and the',
      'manifest is what makes the pair legible without a terminal. If a view would',
      'have to include the corpus to be truthful, it is not a view — narrow the',
      'question until it is not.',
    );
  }

  return lines;
}

function humanFacingViews(): string[] {
  return [
    '## Human-facing views',
    '',
    'When the human says *show me*, *browse*, *review*, *inspect*, *compare*,',
    '*explore*, or *look at* something, consider an A2H view instead of pasting a',
    'path into the reply. A view is a set of workspace files plus a manifest that',
    'tells A2H what those files mean and in what order to show them.',
    '',
    'Two rules keep a view honest:',
    '',
    '- **Role is not content type.** Role is meaning — `spec`, `evidence`,',
    '  `candidate`, `decision`, `draft`. How the bytes are drawn is decided from',
    '  the file itself. A PNG called `final-truth` is still an image; a Markdown',
    '  file called `dataset` is still Markdown. Invent roles freely; none of them',
    '  has to match a file type A2H already knows.',
    '- **High signal only, and bounded.** A view is a curated set, not an export.',
    '',
    'Do not generate HTML for the human, and do not embed JavaScript. A2H renders',
    'Markdown conservatively and does not execute author content, so a hand-written',
    'page is dead weight at best.',
  ];
}

function existingSetup(profile: ProjectProfile): string[] {
  const lines: string[] = ['## Existing A2H setup', ''];

  if (profile.hasManifest) {
    lines.push(
      'This repository already ships `.a2h/manifest.json`. Update it. Do not',
      'replace it with a scaffold inferred from file names, and do not drop the',
      'existing semantics on the floor — the manifest is this project\u2019s accumulated',
      'meaning about its own artifacts, and a regenerated skeleton throws that away.',
      'Add what your work needs: new items, a task a human should judge, an action',
      'they may take. Leave what is already correct alone.',
    );
  } else {
    lines.push(
      'There is no `.a2h/manifest.json` here, and that is a supported state: A2H',
      'infers a presentation from conventions and content, which is enough for a',
      'quick look.',
      '',
      'For anything persistent, create `.a2h/manifest.json` and put meaning in it:',
      'the tasks a human should judge, the artifacts they should read and in what',
      'order, and the actions they may take about the result. Do not leave the',
      'scaffold as the final description — a file of `role: "markdown"` entries',
      'tells a human nothing they could not see in a file listing. This guide does',
      'not run `init` for you; it only tells you not to stop there.',
    );
  }

  lines.push('');
  if (profile.hasAgentsMd) {
    lines.push(
      '`AGENTS.md` exists at the repository root. Rules you want to be permanent',
      'belong there: merge the durable parts of this guidance into it, so the next',
      'agent does not have to rely on this file being regenerated. A2H never writes',
      'or edits `AGENTS.md`, and neither does this guide.',
    );
  } else {
    lines.push(
      'There is no `AGENTS.md` at the repository root. If repository-wide rules for',
      'coding agents should persist, create one and merge the durable parts of this',
      'guidance into it. A2H never writes or edits `AGENTS.md`, and neither does',
      'this guide.',
    );
  }

  return lines;
}

function artifactGuidance(profile: ProjectProfile): string[] {
  const lines: string[] = [
    '## Artifact guidance',
    '',
    '- **Keep every path inside the workspace.** Workspace-relative paths only.',
    '  Absolute paths, `..`, and links that leave the tree are refused, and a claim',
    '  the viewer cannot read is a broken promise to the human.',
    '- **Never put secrets in a previewable file.** Credentials, tokens, and private',
    '  keys do not belong in a workspace someone is about to open. A2H withholds',
    '  what it classifies as sensitive, but that is a backstop, not your control.',
    '- **Be specific in `summary`.** One concrete line — what finished, what is',
    '  blocked, what the human must decide — beats a paragraph of status.',
    '- **Do not invent protocol fields.** The field reference ships with the tool:',
    '  `docs/protocol.md` in the A2H checkout, or the agent skill installed next to',
    '  it. Read that for exact names and shapes. This guide is about judgement, not',
    '  schema.',
  ];

  if (profile.hasSensitiveFiles) {
    lines.push(
      '',
      'The scanner classifies at least one file in this workspace as credential-like.',
      'It was not read to produce this guide. Never copy such a file into a view, name',
      'it in a summary, or quote it in a report — a secret that reaches a',
      'human-readable page is no longer a secret.',
    );
  }

  return lines;
}

function producerWorkflow(): string[] {
  return [
    '## Producer workflow',
    '',
    'Materialize before you present. The order is:',
    '',
    '1. the source of truth — the repository state or the data the work is about;',
    '2. retrieve and filter it down to the part that matters;',
    '3. write small, human-readable artifacts: a summary, a selection, a table, a',
    '   diff, a screenshot, a chart;',
    '4. point `.a2h/manifest.json` at those artifacts, choosing `role`, `group`, and',
    '   `priority` so the reading order is the order you want;',
    '5. run `a2h validate <workspace>`;',
    '6. hand the human the workspace.',
    '',
    'Never go from the source of truth straight to A2H over the whole tree. Someone',
    'who wanted the whole tree would open a file browser; the value here is the',
    'reduction, so do the reduction yourself and let A2H present the result.',
    '',
    'Write the human-facing workspace as the last step of a unit of work and treat',
    'it as part of the work rather than as reporting about it. A task with no',
    'status, no artifacts, and no actions is invisible — and so is a run with no',
    'summary and no steps.',
  ];
}

function validation(): string[] {
  return [
    '## Validation',
    '',
    '`a2h validate <workspace>` is the pre-flight check, and it runs the same loader',
    'the viewer runs, so it cannot disagree with what a human is about to see.',
    '',
    '- Exit **1** — the workspace claims something broken enough to mislead a human:',
    '  an unusable manifest, a claimed path that is missing or that A2H will not',
    '  render, an action id that does not resolve, or a decision file A2H refused to',
    '  read.',
    '- Exit **0** — presentable. Warnings are allowed: no manifest, no tasks,',
    '  producer-defined roles, an action no task points at.',
    '',
    'Fix every error before saying the work is done. Read the warnings; they are',
    'usually the difference between a thin view and a useful one.',
  ];
}

function boundaries(): string[] {
  return [
    '## Important boundaries',
    '',
    '- `.a2h/agent-guide.md` is tooling-generated agent guidance. It is not protocol',
    '  input, it has no authority in the semantic merge, and it is never rendered as',
    '  workspace content.',
    '- A2H never writes or edits `AGENTS.md`. Merging durable rules into it is the',
    '  agent\u2019s job, or the human\u2019s.',
    '- Nothing on this path needs the network. `a2h guide` is offline,',
    '  deterministic, and idempotent: two runs over an unchanged repository produce',
    '  two identical files, byte for byte.',
    '- Paths stay inside the workspace, and secrets never enter a previewable file.',
    '- A2H presents; it does not decide. Approval, rejection, and retries happen',
    '  through declared actions, and the executor\u2019s own policy is authoritative for',
    '  what an action may do.',
  ];
}
